### ISSUE TITLE
Postback with referral

### ISSUE THREAD

**Issue by mfvitale** [fyndme/messenger-bot-tester#2]
Hi, 

is there a way to send a postback with referral informations? https://developers.facebook.com/docs/messenger-platform/webhook-reference/postback

Thanks.

**Comment by adamjuhasz** [comment]
Shouldn't be too hard to add a new check to the responses files, want to try a PR?

**Comment by mfvitale** [comment]
I added the following:

-`export interface PostbackWithReferral extends Message {
    postback: {
        payload: string;
        referral: {
            ref: string,
            source: string,
            type: string,
        }
    };
}` 
in webhook-types.ts

-`export class PostbackMessageWithReferral extends Message {
    protected payload: types.PostbackWithReferral;
    public create(payload: string, referral: string): this {
        this.payload = {
            sender: {
                id: this.sender,
            },
            recipient: {
                id: this.recipient,
            },
            timestamp: (new Date).getTime(),
            postback: {
                payload: payload,
                referral: {
                    ref: referral,
                    source: "SHORTLINK",
                    type: "OPEN_THREAD",
                }
            },
        };
        return this;
    }
}`
in messages.ts

-` public sendPostbackMessageWithReferral(payload: string, referral: string): this {
        this.script.push(new PostbackMessageWithReferral(this.userID, this.pageID, this.seq++).create(payload, referral));
        return this;
    }`

in index.ts

but when I run npm test or tsc i get this error:

index.ts(225,30): error TS2304: Cannot find name 'PostbackMessageWithReferral'.

Any suggestion?

Thanks.

**Comment by mfvitale** [comment]
Hi Adam, 

I cloned your repo and did the change. How can i do a pull request? Thanks.

**Comment by adamjuhasz** [comment]
Thanks for the PR(#3)! I just updated to ver 1.3.1 on npm.

**Comment by mfvitale** [comment]
Thanks!
