### ISSUE TITLE
Timeout of 2000ms exceeded.

### ISSUE THREAD

**Issue by OverVlad** [fyndme/messenger-bot-tester#4]
When start tests I get an error.

`Error: Timeout of 2000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves.`

Code i copy in README

**Comment by adamjuhasz** [comment]
I need more context to help you

**Comment by OverVlad** [comment]
@adamjuhasz when test-server send request for my bot, i have an error:
`SyntaxError: Unexpected token O in JSON at position 0
    at JSON.parse (<anonymous>)
    at IncomingMessage.response.on (/Users/Vladislau/Documents/Web/fb-messenger-bot-template/node_modules/tiny_request/lib/network.js:70:40)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickDomainCallback (internal/process/next_tick.js:122:9)`

**Comment by adamjuhasz** [comment]
What is the bot-tester code you're using?

**Comment by OverVlad** [comment]
@adamjuhasz 
const BotTester = require('messenger-bot-tester');

describe('bot test', function() {
  // webHookURL points to where yout bot is currently listening
  // choose a port for the test framework to listen on
  const testingPort = 3100;
  const webHookURL = 'http://localhost:7000/fbwebhook';
  const tester = new BotTester.default(testingPort, webHookURL);

  before(function(){
    // start your own bot here or having it running already in the background
    // redirect all Facebook Requests to http://localhost:3100/v2.6 and not https://graph.facebook.com/v2.6
    return tester.startListening();
  });

  it('WELCOME postback', () => {
    const theScript = new BotTester.Script('132', '1212244745534496');
    theScript.sendPostbackMessage('WELCOME');
    theScript.expectTextResponses([
      "Hey there! Welcome to the BotCube 🤖 bot! I'm a basic, menu-based bot who will help you to explore bot possibilities.",
      "If you are looking to build bots or learn more about messaging apps, please schedule a chat with real humans 🙂."
    ]);

    return tester.runScript(theScript);
  });
})

**Comment by adamjuhasz** [comment]
Is that error coming from your bot code?

**Comment by OverVlad** [comment]
@adamjuhasz error from package tiny_request

**Comment by adamjuhasz** [comment]
So you get the postback from the tester and when you send a text response through tiny_request from your bot to the tester, you get a JSON error?

**Comment by OverVlad** [comment]
Yes. I have json error when i parse json from the tester request 
In line:
`var obj = JSON.parse(data)`

**Comment by adamjuhasz** [comment]
can you show me the output of `console.log(data)` so I can see what the framework is sending

**Comment by OverVlad** [comment]
console.log(data) => 'OK'

**Comment by adamjuhasz** [comment]
Weird, I don't see where that could be sent from. I can look at the code later tonight more in depth

**Comment by OverVlad** [comment]
@adamjuhasz I delete tiny_request  package and now it work!
