### ISSUE TITLE
Missing sendQuickReplyMessage

### ISSUE THREAD

**Issue by FrancescoDalan** [fyndme/messenger-bot-tester#7]
Hello,
in readme you wrote that QuickMessage is managed but in index.ts I can't found the method. 

If you want, I implemented the method locally and I can share my code with you. Can I have the access to your repository?

**Comment by ajuhaszcf** [comment]
Feel free to send a PR!

**Comment by FrancescoDalan** [comment]
Sorry Adam,
but when I try to compile the master branch, I have this errors:

node_modules/@types/bluebird/index.d.ts(925,37): error TS2304: Cannot find name 'Iterable'.
node_modules/@types/bluebird/index.d.ts(925,69): error TS2304: Cannot find name 'Iterable'.
node_modules/@types/bluebird/index.d.ts(948,37): error TS2304: Cannot find name 'Iterable'.
node_modules/@types/bluebird/index.d.ts(948,69): error TS2304: Cannot find name 'Iterable'.
node_modules/@types/bluebird/index.d.ts(955,38): error TS2304: Cannot find name 'Iterable'.
node_modules/@types/bluebird/index.d.ts(955,70): error TS2304: Cannot find name 'Iterable'.
node_modules/@types/bluebird/index.d.ts(965,38): error TS2304: Cannot find name 'Iterable'.
node_modules/@types/bluebird/index.d.ts(965,70): error TS2304: Cannot find name 'Iterable'.
node_modules/@types/bluebird/index.d.ts(1021,27): error TS2304: Cannot find name 'Iterable'.
node_modules/@types/bluebird/index.d.ts(1021,59): error TS2304: Cannot find name 'Iterable'.
node_modules/@types/bluebird/index.d.ts(1036,27): error TS2304: Cannot find name 'Iterable'.
node_modules/@types/bluebird/index.d.ts(1036,59): error TS2304: Cannot find name 'Iterable'.
node_modules/@types/bluebird/index.d.ts(1050,27): error TS2304: Cannot find name 'Iterable'.
node_modules/@types/bluebird/index.d.ts(1050,59): error TS2304: Cannot find name 'Iterable'.
node_modules/@types/bluebird/index.d.ts(1063,27): error TS2304: Cannot find name 'Iterable'.
node_modules/@types/bluebird/index.d.ts(1063,59): error TS2304: Cannot find name 'Iterable'.
node_modules/@types/bluebird/index.d.ts(1077,27): error TS2304: Cannot find name 'Iterable'.
node_modules/@types/bluebird/index.d.ts(1077,59): error TS2304: Cannot find name 'Iterable'.

Can you help me?
Thank you

**Comment by ajuhaszcf** [comment]
Looks like there may be a version mismatch in the type definitions, I would try a delete, re-install of dips
